<?php

/**
 * @file
 * Contains d8_routes.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function d8_routes_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the d8_routes module.
    case 'help.page.d8_routes':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('SAmple console') . '</p>';
      return $output;

    default:
  }
}
